### ISSUE TITLE
Formalize and implement a clear Node.js version support policy

### ISSUE THREAD

**Issue by thomvaill** [thomvaill/log4brains#122]
# Context

I (the maintainer) was absent from the project for a long time (see https://github.com/thomvaill/log4brains/discussions/108#discussioncomment-10768555) so now the project runs only up to Node.js v16, which is not supported anymore since September 2023.
Also, as @jean-francoismougnot mentioned in https://github.com/thomvaill/log4brains/discussions/108#discussioncomment-10545389: [Github Actions dropped support of Node 16](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)

There were also some Issues and PR created earlier related to this topic:

- https://github.com/thomvaill/log4brains/pull/114
- https://github.com/thomvaill/log4brains/issues/117
- https://github.com/thomvaill/log4brains/issues/106
- https://github.com/thomvaill/log4brains/issues/85

# Action plan

To make a fresh start, here is a proposal of action plan.
This issue can be considered as an epic; feel free to raise a PR for each item.

- [x] test and merge https://github.com/thomvaill/log4brains/pull/114 to support Node.js v18 -> @thomvaill 
- [x] fix the CI
- [x] write a formalized Node.js version support policy in README.md and CONTRIBUTING.md: I propose to officially support the "active" and "maintenance" LTS versions (see https://nodejs.org/en/about/previous-releases), and to support in a best effort mode the "current" version
- [x] test and make log4brains work on Node v22, and if possible v23 (but best effort)
- [x] optional: automatize the creation of an issue when a new LTS version is available so we don't forget to support it

**Comment by Potherca** [comment]
Regarding the version support policy and NodeJS version tracking (for possible automation), the [nodejs/Release repo](https://github.com/nodejs/Release) contains a [JSON that describes releases](https://raw.githubusercontent.com/nodejs/Release/refs/heads/main/schedule.json).

As the CI already uses a `matrix` to run different NodeJS versions, we _could_ add unstable versions but `allow_failures`, to get an idea of incoming breakage without actually breaking the build.

**Comment by apankratiev-syberry** [comment]
Speaking about dependencies in general. 
Maybe you have any plans to introduce dependabot/renovate? 
Considering that the project has good tests coverage, you could even enable automerge of minor/path dependencies updates

**Comment by Potherca** [comment]
I'd be interested in other peoples opinions on this before I speak my mind... There are pros and cons, but I is worth discussing, IMHO.

**Comment by thomvaill** [comment]
I think it is indeed a good idea, especially for a package that is distributed by an `npm install -g`.
We already had some issues because of "lax" semver dependencies in the package.json so I already opened this debate a long time ago here: https://github.com/thomvaill/log4brains/discussions/33
Since using renovate involves pinning all the dependencies to strict versions, it would also solve the issue I mentioned in the discussion.
So yes I would totally be in favor of using this tool.
I you are OK with this, I'll edit this post to this task in the action plan at the end (the first steps are more urgent).
But I'd like to hear your thoughts about this first.

**Comment by thomvaill** [comment]
Hi all,
I've been progressing well on this issue.

# Already merged PRs

Sorry I had to merge them without reviews to be able to progress fast + it was quite hard to debug lerna in the CI so it was easier.

Make Log4brains work on Node 18 and 20:
- https://github.com/thomvaill/log4brains/pull/124 : the main one
- https://github.com/thomvaill/log4brains/pull/125 : had the move the workaround somewhere else

CI fixes for the new workflow (https://github.com/thomvaill/log4brains/pull/121):
- https://github.com/thomvaill/log4brains/pull/126
- https://github.com/thomvaill/log4brains/pull/127
- https://github.com/thomvaill/log4brains/pull/128
- https://github.com/thomvaill/log4brains/pull/129

# PR waiting for reviews

The main topic of this issue:

- https://github.com/thomvaill/log4brains/pull/130 -> once merged, should automatically create a new Issue for the new Node.js LTS v22 which entered in active state yesterday (as @Potherca suggested)

Thanks!

# New related issues created during this development

- https://github.com/thomvaill/log4brains/issues/131 (as @apankratiev-syberry suggested)
- https://github.com/thomvaill/log4brains/issues/132
- https://github.com/thomvaill/log4brains/issues/133

**Comment by thomvaill** [comment]
Fixed in [v1.1.0](https://github.com/thomvaill/log4brains/releases/tag/v1.1.0) 😃
